### PR TITLE
Support passwords with # character

### PR DESCRIPTION
**Pull request by esapozhnikov**
This update corrects the syntax for monitoring remote targets via new version of freeipmi.

### CODE REVIEW

**Comment by esapozhnikov** [comment]
Any Updated on this?
@bitfehler

**Comment by bitfehler** [comment]
@esapozhnikov Now! :smile_cat: 
Sorry it took so long. Now, first of all I need to point out that I have some reservations about this:
 - we explicitly removed the exact behavior you are re-introducing here in https://github.com/soundcloud/ipmi_exporter/commit/e11e76ed5c059edc752a101fb600a393d73d776a because it is bad security practice - I would very much like to avoid re-introducing it unless absolutely necessary, and even then it would have to made an explicit option, not the default
 - Freeipmi 1.4.5 is not exactly the "current version" - it is almost five years old, with lots of newer versions available (see https://www.gnu.org/software/freeipmi/index.html)

That said, I would of course very much like to help you get it working. I checked the man pages of [version 1.4.5](https://ftp.gnu.org/gnu/freeipmi/freeipmi-1.4.5.tar.gz) and that version already supports passing username and password in the config file, so I still don't understand why this doesn't work out of the box. There is a few things we could try, though:
 - Try a newer version of freeipmi - if this is an option for you, I think it would be good in any case
 - Maybe you can add debug statement [here](https://github.com/soundcloud/ipmi_exporter/blob/master/collector.go#L186) that prints the output of `freeipmiConfig(...)` and verify that it is what you would expect
 - We could also work backwards: create a small config file like this:
   ```
   driver-type LAN_2_0
   privilege-level admin
   username <USER>
   password <PASSWORD>
   session-timeout 2500
   ```
   and try the following command: `ipmi-sensors -h <IP> -Q --comma-separated-output --no-header-output --sdr-cache-recreate --config-file <FILE>` where `<FILE>` is the above file. If that works, there is something amiss in the exporter. If it doesn't work, maybe try running with `ipmi-sensors --debug ...` and post the output here.

Sorry, I assume that this is not very satisfying, but I think there is some underlying issue that I'm not seeing yet. But I don't think just going back to command line arguments is a good solution.

Also, could you maybe post the OS and version that all this is happening on?

Thanks again for your patience while we work this out!

**Comment by Cmdrd** [comment]
Just recently came across this issue with a number of servers that were deployed. The cause in this case appears to be that certain special characters in the password break the FreeIPMI tools when loading the passwords in via the config file whereas loading them through the command line flags worked fine (ie. specifying -p/--password) like @esapozhnikov was experiencing. Alphanumeric passwords with mixed cases did not appear to cause any issues.

This is with tools version 1.4.11, which is fairly outdated, on Ubuntu 18.04. Will test with newer versions and also poke through the patch notes from 1.4.11 to see if this issue was identified and possibly resolved for reference.

**Comment by bitfehler** [comment]
Oh, interesting! Thanks a lot for digging into this! I'll also run some tests myself. I assume this could also be a matter of file encoding? Can you possibly provide a single example character that breaks this and let me know if it works for you if you create the config file with a regular editor and have FreeIPMI use that? In that case it would actually be a bug in the exporter...

**Comment by Cmdrd** [comment]
It appears that the '#' character broke things using the config file, unfortunately have not had a chance to test other characters to determine if it is all special characters or just a subset. It could be en encoding issue but I think the issue lies with FreeIPMI versus the collector as running commands such as the following result in an error with the offending special character but works without it:

`bmc-info -h <server_ip> --config-file config_file`
`bmc-info: password invalid`

**Comment by esapozhnikov** [comment]
Ahh that did not occur to me. 
I can also confirm that our passwords do include the `#`

**Comment by bitfehler** [comment]
Thanks @Cmdrd @esapozhnikov for the investigation! I finally got around to reproducing this, and the fix is actually rather simple - just escape any `#` in the password with a backslash. I added a fix to the master branch. Can you please confirm that using the current master fixes your problems?

**Pull request closed without merging**
