### PR TITLE
Add Prometheus-style makefile for building and publishing.

### PR DESCRIPTION
**Pull request by SuperQ**
* Use the Prometheus standard build setup.

### CODE REVIEW

**Comment by SuperQ** [comment]
Need to enable CircelCI for this repo, for publishing, a GitHub API key is needed in the CircleCI env.

**Comment by bitfehler** [comment]
So with this config you would do a release by adding a tag that matches `/^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/`?

**Comment by grobie** [comment]
Unfortunately, we won't be able to support CircleCI here, as they still haven't upgraded their Github integration to Github apps from the old OAuth app model. The old integration doesn't allow us to restrict access to specific repos, or just to public repositories, and would grant CircleCI access to all private repos as well.

**Comment by SuperQ** [comment]
@grobie That sucks. Can we do this with Travis?

**Comment by grobie** [comment]
It does indeed. I'd love to use CircleCI for our public integrations. TravisCI is also still using the old integration which doens't provide fine-grained access control.

What we have used for recent open-source projects is https://cirrus-ci.org/ for that reason.

**Comment by SuperQ** [comment]
@bitfehler Doing a release would be similar to how we do [Prometheus releases](https://github.com/prometheus/prometheus/blob/master/RELEASE.md).

Basically, you just need to create the git tag, and the pipeline triggers do most of the work. The lastest version of the tool even creates the github release draft, so all you have to do is click the publish button.

**Comment by SuperQ** [comment]
@grobie Thanks, I guess I can re-work this PR to use cirrus-ci.

Or, maybe for now, just include the build improvements and do the CI work separately.

**Comment by grobie** [comment]
Thanks for your work @SuperQ. I'll leave the rest of the CI setup to you and @bitfehler. I'm happy to help out with the Cirrus access, but @bitfehler might be able to do that on his own already.

Here is an example project with a Cirrus config: https://github.com/soundcloud/twinagle/blob/master/.cirrus.yml

**Comment by bitfehler** [comment]
Let's do it, this has been stable enough that we start working towards proper releases (#24). I'll try look into CirrusCI asap, but if you have anything ready feel free to open another PR :wink: 
Thanks!

**Pull request merged**
